[package]
name = "steamos-manager-proxy"
version = "25.7.0"
edition = "2021"
repository = "https://gitlab.steamos.cloud/holo/steamos-manager/"

[dependencies]
zbus = { version = "5", default-features = false, features = ["tokio"] }
